name:                diceroller
version:             0.1.0.0
github:              "herulume/diceroller"
license:             BSD3
author:              "Eduardo Barbosa"
maintainer:          "example@example.com"
copyright:           "2018 Eduardo Barbosa"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/herulume/diceroller#readme>

dependencies:
- base >= 4.7 && < 5
- random
- split
- criterion
library:
  source-dirs: src

executables:
  diceroller-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - diceroller

tests:
  diceroller-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - diceroller
